##################################################################################################
# ProductPage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
---
##################################################################################################
# Productpage deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
        - name: productpage
          image: felixatope32/07-productpage:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          securityContext:
            runAsUser: 1000
          env:
            - name: DETAILS
              value: "details:9080"
            - name: REVIEWS
              value: "reviews:9080"
---
##################################################################################################
# LoadBalancer service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-external
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
    - name: http
      port: 9080
      targetPort: 9080
---
